[package]
name = "vfs"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
serde = "1.0.228"
serde_derive = "1.0.228"
idle = { version = "0.1.0", path = "../idle" }
