[package]
name = "vfs"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
serde.workspace = true
serde_derive.workspace = true
idle = { version = "0.1.0", path = "../idle" }
