[package]
name = "define_requests"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
iter_ext = { version = "0.1.0", path = "../iter_ext" }
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.110", features = ["full"] }
