[package]
name = "adept"
version = "0.1.0"
edition = "2024"

[dependencies]
daemon_init = { version = "0.1.0", path = "../daemon_init" }
language_server = { version = "0.1.0", path = "../language_server" }
smol.workspace = true

