[workspace]
resolver = "3"
members = [
    "src/adept",
    "src/components/req",
    "src/components/vfs",
    "src/components/daemon",
    "src/support/define_requests",
    "src/support/iter_ext",
    "src/support/top_n",
    "src/support/infinite_iterator",
    "src/support/line_column",
    "src/support/text",
]

