[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
lock_file = { version = "0.1.0", path = "../lock_file" }
daemon_scheduler = { version = "0.1.0", path = "../daemon_scheduler" }
smol.workspace = true
thiserror.workspace = true
