[package]
name = "ipc_message"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.145"
text_edit = { version = "0.1.0", path = "../../representations/text_edit" }
vfs = { version = "0.1.0", path = "../../components/vfs" }

