[package]
name = "request"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode.workspace = true
build_aon = { version = "0.1.0", path = "../build_aon" }
build_token = { version = "0.1.0", path = "../build_token" }
by_address.workspace = true
define_requests = { version = "0.1.0", path = "../../support/define_requests" }
derive_more.workspace = true
infinite_iterator = { version = "0.1.0", path = "../../support/infinite_iterator" }
line_column = { version = "0.1.0", path = "../../support/line_column" }
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
text = { version = "0.1.0", path = "../../support/text" }
thiserror.workspace = true
token = { version = "0.1.0", path = "../../representations/token" }
top_n = { version = "0.1.0", path = "../../support/top_n" }
vfs = { version = "0.1.0", path = "../vfs" }
idle = { version = "0.1.0", path = "../idle" }
text_edit = { version = "0.1.0", path = "../../representations/text_edit" }
fingerprint = { version = "0.1.0", path = "../../representations/fingerprint" }
