[package]
name = "token"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative.workspace = true
derive_more.workspace = true
infinite_iterator = { version = "0.1.0", path = "../../support/infinite_iterator" }
num-bigint.workspace = true
