[package]
name = "language_server"
version = "0.1.0"
edition = "2024"

[dependencies]
lsp-types = "0.97.0"
request = { version = "0.1.0", path = "../request" }
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
vfs = { version = "0.1.0", path = "../vfs" }
daemon = { version = "0.1.0", path = "../daemon" }
