[package]
name = "language_server"
version = "0.1.0"
edition = "2024"

[dependencies]
lsp-types = "0.97.0"
request = { version = "0.1.0", path = "../request" }
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
vfs = { version = "0.1.0", path = "../vfs" }
daemon = { version = "0.1.0", path = "../daemon" }
ipc_message = { version = "0.1.0", path = "../../representations/ipc_message" }
text_edit = { version = "0.1.0", path = "../../representations/text_edit" }
fingerprint = { version = "0.1.0", path = "../../representations/fingerprint" }
transport = { version = "0.1.0", path = "../../components/transport" }
smol.workspace = true
pin-project-lite.workspace = true

