[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.1"
nix = { version = "0.30.1", features = ["fs"] }
req = { version = "0.1.0", path = "../req" }
smol = "2.0.2"
vfs = { version = "0.1.0", path = "../vfs" }

